### ISSUE TITLE
opencv_calib3d230.lib missing from VC10 libs

### ISSUE THREAD

**Issue by momo-the-monster** [cinder/Cinder-OpenCV#1]
The debug version is included, but not the release version. Is there a reason for this, or was it an oversight?

**Comment by andrewfb** [comment]
Sorry about that - does this commit fix it for you? https://github.com/cinder/Cinder-OpenCV/commit/1133ec82d304fd72cde5783daedb5d706e10073f

**Comment by momo-the-monster** [comment]
That's great - thanks for the quick response! I actually went ahead and integrated openCV 2.3.1 into my project, but it's great to have the official download be complete.
